[project]
name = "advent-of-code-2024"
version = "0.1.0"
description = "Solutions for advent of code 2024"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.1.3",
    "pandas>=2.2.3",
]

[dependency-groups]
dev = [
    "ruff>=0.8.1",
]
